#!/usr/bin/env python3

"""
register.py - A helper script to register compiled ABIs to the backend server. Note an ABI id
                is generated by the backend server and is used to identify the ABI. An ABI id
                of 0 refers to the DatasetManager ABI.

Usage:
    python register.py

Dependencies:
    pip install requests
"""

import os
import json
import requests

BASE_URL = "http://localhost:5000"

# register an account
def register_account():
    url = BASE_URL + "/api/user"

    data = {"username": "abi_register_script", "password": "abi_register_script"}

    response = requests.post(url, json=data)

    assert response.status_code == 200


# login to an account and return the session token
def login():
    url = BASE_URL + "/api/session"

    data = {"username": "abi_register_script", "password": "abi_register_script"}

    response = requests.post(url, json=data)

    assert response.status_code == 200

    return response.cookies


# register an ABI
def register_abi(name, abi_path, cookies):
    url = BASE_URL + "/api/abi"

    with open(abi_path, "r") as f:
        abi = json.load(f)

    data = {"name": name, "abi": abi.get("abi")}

    response = requests.post(url, json=data, cookies=cookies)

    assert response.status_code == 200

    print("Registered ABI: " + name)


# register all ABIs in the build/ folder
def register_all_abis(cookies):
    for file in os.listdir("build/"):
        if file.endswith(".json") and not file.startswith("Migrations"):
            name = file.split(".")[0]
            abi_path = "build/" + file
            register_abi(name, abi_path, cookies)


# delete user account
def delete_account(cookies):
    url = BASE_URL + "/api/user"

    response = requests.delete(url, cookies=cookies)

    assert response.status_code == 200


# logout of account
def logout(cookies):
    url = BASE_URL + "/api/session"

    response = requests.delete(url, cookies=cookies)

    assert response.status_code == 200


if __name__ == "__main__":
    print("Registering ABIs...")
    register_account()
    cookies = login()
    register_all_abis(cookies)
    delete_account(cookies)
    logout(cookies)
